-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MNIST_PointwiseConv2d_4_4_12_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    depth2_o77_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    depth2_o77_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    depth2_o77_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    depth2_o77_empty_n : IN STD_LOGIC;
    depth2_o77_read : OUT STD_LOGIC;
    weights_0_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_0_ce0 : OUT STD_LOGIC;
    weights_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_0_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_0_ce1 : OUT STD_LOGIC;
    weights_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_1_ce0 : OUT STD_LOGIC;
    weights_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_1_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_1_ce1 : OUT STD_LOGIC;
    weights_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_2_ce0 : OUT STD_LOGIC;
    weights_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_2_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_2_ce1 : OUT STD_LOGIC;
    weights_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_3_ce0 : OUT STD_LOGIC;
    weights_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_3_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_3_ce1 : OUT STD_LOGIC;
    weights_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_4_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_4_ce0 : OUT STD_LOGIC;
    weights_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_4_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_4_ce1 : OUT STD_LOGIC;
    weights_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_5_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_5_ce0 : OUT STD_LOGIC;
    weights_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_5_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_5_ce1 : OUT STD_LOGIC;
    weights_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_6_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_6_ce0 : OUT STD_LOGIC;
    weights_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_6_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_6_ce1 : OUT STD_LOGIC;
    weights_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_7_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_7_ce0 : OUT STD_LOGIC;
    weights_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_7_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_7_ce1 : OUT STD_LOGIC;
    weights_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_8_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_8_ce0 : OUT STD_LOGIC;
    weights_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_8_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_8_ce1 : OUT STD_LOGIC;
    weights_8_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_9_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_9_ce0 : OUT STD_LOGIC;
    weights_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_9_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_9_ce1 : OUT STD_LOGIC;
    weights_9_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_10_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_10_ce0 : OUT STD_LOGIC;
    weights_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_10_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_10_ce1 : OUT STD_LOGIC;
    weights_10_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_11_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_11_ce0 : OUT STD_LOGIC;
    weights_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_11_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_11_ce1 : OUT STD_LOGIC;
    weights_11_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_12_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_12_ce0 : OUT STD_LOGIC;
    weights_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weights_12_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
    weights_12_ce1 : OUT STD_LOGIC;
    weights_12_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    point2_o78_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    point2_o78_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    point2_o78_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    point2_o78_full_n : IN STD_LOGIC;
    point2_o78_write : OUT STD_LOGIC );
end;


architecture behav of MNIST_PointwiseConv2d_4_4_12_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal weights_0_load_reg_574 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal weights_1_load_reg_579 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_2_load_reg_584 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_3_load_reg_589 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_4_load_reg_594 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_5_load_reg_599 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_6_load_reg_604 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_7_load_reg_609 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_8_load_reg_614 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_9_load_reg_619 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_10_load_reg_624 : STD_LOGIC_VECTOR (31 downto 0);
    signal weights_11_load_reg_629 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_done : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_idle : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_ready : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_depth2_o77_read : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_ce0 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_address1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_ce1 : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1118_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1118_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1017_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1017_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_916_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_916_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_815_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_815_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_714_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_714_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_613_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_613_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_512_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_512_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_411_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_411_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_310_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_310_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_29_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_29_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_18_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_18_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add277_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add277_out_ap_vld : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_done : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_idle : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_ready : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_point2_o78_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_point2_o78_write : STD_LOGIC;
    signal grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln9_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal indvar_flatten_fu_68 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln9_fu_376_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component MNIST_PointwiseConv2d_4_4_12_Pipeline_ic IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        depth2_o77_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        depth2_o77_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        depth2_o77_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        depth2_o77_empty_n : IN STD_LOGIC;
        depth2_o77_read : OUT STD_LOGIC;
        weights_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_0_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_0_ce0 : OUT STD_LOGIC;
        weights_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_0_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_0_ce1 : OUT STD_LOGIC;
        weights_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_1_ce0 : OUT STD_LOGIC;
        weights_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_1_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_1_ce1 : OUT STD_LOGIC;
        weights_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_2_ce0 : OUT STD_LOGIC;
        weights_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_2_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_2_ce1 : OUT STD_LOGIC;
        weights_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_12_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_12_ce0 : OUT STD_LOGIC;
        weights_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_12_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_12_ce1 : OUT STD_LOGIC;
        weights_12_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_3_ce0 : OUT STD_LOGIC;
        weights_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_3_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_3_ce1 : OUT STD_LOGIC;
        weights_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_4_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_4_ce0 : OUT STD_LOGIC;
        weights_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_4_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_4_ce1 : OUT STD_LOGIC;
        weights_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_5_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_5_ce0 : OUT STD_LOGIC;
        weights_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_5_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_5_ce1 : OUT STD_LOGIC;
        weights_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_6_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_6_ce0 : OUT STD_LOGIC;
        weights_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_6_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_6_ce1 : OUT STD_LOGIC;
        weights_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_7_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_7_ce0 : OUT STD_LOGIC;
        weights_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_7_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_7_ce1 : OUT STD_LOGIC;
        weights_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_8_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_8_ce0 : OUT STD_LOGIC;
        weights_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_8_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_8_ce1 : OUT STD_LOGIC;
        weights_8_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_9_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_9_ce0 : OUT STD_LOGIC;
        weights_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_9_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_9_ce1 : OUT STD_LOGIC;
        weights_9_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_10_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_10_ce0 : OUT STD_LOGIC;
        weights_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_10_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_10_ce1 : OUT STD_LOGIC;
        weights_10_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_11_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_11_ce0 : OUT STD_LOGIC;
        weights_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        weights_11_address1 : OUT STD_LOGIC_VECTOR (1 downto 0);
        weights_11_ce1 : OUT STD_LOGIC;
        weights_11_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_1118_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_1118_out_ap_vld : OUT STD_LOGIC;
        add27_1017_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_1017_out_ap_vld : OUT STD_LOGIC;
        add27_916_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_916_out_ap_vld : OUT STD_LOGIC;
        add27_815_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_815_out_ap_vld : OUT STD_LOGIC;
        add27_714_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_714_out_ap_vld : OUT STD_LOGIC;
        add27_613_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_613_out_ap_vld : OUT STD_LOGIC;
        add27_512_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_512_out_ap_vld : OUT STD_LOGIC;
        add27_411_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_411_out_ap_vld : OUT STD_LOGIC;
        add27_310_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_310_out_ap_vld : OUT STD_LOGIC;
        add27_29_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_29_out_ap_vld : OUT STD_LOGIC;
        add27_18_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add27_18_out_ap_vld : OUT STD_LOGIC;
        add277_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add277_out_ap_vld : OUT STD_LOGIC );
    end component;


    component MNIST_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        point2_o78_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        point2_o78_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        point2_o78_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        point2_o78_full_n : IN STD_LOGIC;
        point2_o78_write : OUT STD_LOGIC;
        add277_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_18_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_29_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_310_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_411_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_512_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_613_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_714_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_815_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_916_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_1017_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add27_1118_reload : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288 : component MNIST_PointwiseConv2d_4_4_12_Pipeline_ic
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start,
        ap_done => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_done,
        ap_idle => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_idle,
        ap_ready => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_ready,
        depth2_o77_dout => depth2_o77_dout,
        depth2_o77_num_data_valid => ap_const_lv2_0,
        depth2_o77_fifo_cap => ap_const_lv2_0,
        depth2_o77_empty_n => depth2_o77_empty_n,
        depth2_o77_read => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_depth2_o77_read,
        weights_0_load => weights_0_load_reg_574,
        weights_1_load => weights_1_load_reg_579,
        weights_2_load => weights_2_load_reg_584,
        weights_3_load => weights_3_load_reg_589,
        weights_4_load => weights_4_load_reg_594,
        weights_5_load => weights_5_load_reg_599,
        weights_6_load => weights_6_load_reg_604,
        weights_7_load => weights_7_load_reg_609,
        weights_8_load => weights_8_load_reg_614,
        weights_9_load => weights_9_load_reg_619,
        weights_10_load => weights_10_load_reg_624,
        weights_11_load => weights_11_load_reg_629,
        weights_0_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_address0,
        weights_0_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_ce0,
        weights_0_q0 => weights_0_q0,
        weights_0_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_address1,
        weights_0_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_ce1,
        weights_0_q1 => weights_0_q1,
        weights_1_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_address0,
        weights_1_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_ce0,
        weights_1_q0 => weights_1_q0,
        weights_1_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_address1,
        weights_1_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_ce1,
        weights_1_q1 => weights_1_q1,
        weights_2_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_address0,
        weights_2_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_ce0,
        weights_2_q0 => weights_2_q0,
        weights_2_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_address1,
        weights_2_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_ce1,
        weights_2_q1 => weights_2_q1,
        weights_12_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_address0,
        weights_12_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_ce0,
        weights_12_q0 => weights_12_q0,
        weights_12_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_address1,
        weights_12_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_ce1,
        weights_12_q1 => weights_12_q1,
        weights_3_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_address0,
        weights_3_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_ce0,
        weights_3_q0 => weights_3_q0,
        weights_3_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_address1,
        weights_3_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_ce1,
        weights_3_q1 => weights_3_q1,
        weights_4_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_address0,
        weights_4_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_ce0,
        weights_4_q0 => weights_4_q0,
        weights_4_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_address1,
        weights_4_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_ce1,
        weights_4_q1 => weights_4_q1,
        weights_5_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_address0,
        weights_5_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_ce0,
        weights_5_q0 => weights_5_q0,
        weights_5_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_address1,
        weights_5_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_ce1,
        weights_5_q1 => weights_5_q1,
        weights_6_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_address0,
        weights_6_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_ce0,
        weights_6_q0 => weights_6_q0,
        weights_6_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_address1,
        weights_6_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_ce1,
        weights_6_q1 => weights_6_q1,
        weights_7_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_address0,
        weights_7_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_ce0,
        weights_7_q0 => weights_7_q0,
        weights_7_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_address1,
        weights_7_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_ce1,
        weights_7_q1 => weights_7_q1,
        weights_8_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_address0,
        weights_8_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_ce0,
        weights_8_q0 => weights_8_q0,
        weights_8_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_address1,
        weights_8_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_ce1,
        weights_8_q1 => weights_8_q1,
        weights_9_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_address0,
        weights_9_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_ce0,
        weights_9_q0 => weights_9_q0,
        weights_9_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_address1,
        weights_9_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_ce1,
        weights_9_q1 => weights_9_q1,
        weights_10_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_address0,
        weights_10_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_ce0,
        weights_10_q0 => weights_10_q0,
        weights_10_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_address1,
        weights_10_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_ce1,
        weights_10_q1 => weights_10_q1,
        weights_11_address0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_address0,
        weights_11_ce0 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_ce0,
        weights_11_q0 => weights_11_q0,
        weights_11_address1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_address1,
        weights_11_ce1 => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_ce1,
        weights_11_q1 => weights_11_q1,
        add27_1118_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1118_out,
        add27_1118_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1118_out_ap_vld,
        add27_1017_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1017_out,
        add27_1017_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1017_out_ap_vld,
        add27_916_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_916_out,
        add27_916_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_916_out_ap_vld,
        add27_815_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_815_out,
        add27_815_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_815_out_ap_vld,
        add27_714_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_714_out,
        add27_714_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_714_out_ap_vld,
        add27_613_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_613_out,
        add27_613_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_613_out_ap_vld,
        add27_512_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_512_out,
        add27_512_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_512_out_ap_vld,
        add27_411_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_411_out,
        add27_411_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_411_out_ap_vld,
        add27_310_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_310_out,
        add27_310_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_310_out_ap_vld,
        add27_29_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_29_out,
        add27_29_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_29_out_ap_vld,
        add27_18_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_18_out,
        add27_18_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_18_out_ap_vld,
        add277_out => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add277_out,
        add277_out_ap_vld => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add277_out_ap_vld);

    grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344 : component MNIST_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start,
        ap_done => grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_done,
        ap_idle => grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_idle,
        ap_ready => grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_ready,
        point2_o78_din => grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_point2_o78_din,
        point2_o78_num_data_valid => ap_const_lv2_0,
        point2_o78_fifo_cap => ap_const_lv2_0,
        point2_o78_full_n => point2_o78_full_n,
        point2_o78_write => grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_point2_o78_write,
        add277_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add277_out,
        add27_18_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_18_out,
        add27_29_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_29_out,
        add27_310_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_310_out,
        add27_411_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_411_out,
        add27_512_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_512_out,
        add27_613_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_613_out,
        add27_714_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_714_out,
        add27_815_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_815_out,
        add27_916_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_916_out,
        add27_1017_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1017_out,
        add27_1118_reload => grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_add27_1118_out);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln9_fu_370_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_ready = ap_const_logic_1)) then 
                    grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln9_fu_370_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_ready = ap_const_logic_1)) then 
                    grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_fu_68 <= ap_const_lv5_0;
            elsif (((icmp_ln9_fu_370_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                indvar_flatten_fu_68 <= add_ln9_fu_376_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                weights_0_load_reg_574 <= weights_0_q0;
                weights_10_load_reg_624 <= weights_10_q0;
                weights_11_load_reg_629 <= weights_11_q0;
                weights_1_load_reg_579 <= weights_1_q0;
                weights_2_load_reg_584 <= weights_2_q0;
                weights_3_load_reg_589 <= weights_3_q0;
                weights_4_load_reg_594 <= weights_4_q0;
                weights_5_load_reg_599 <= weights_5_q0;
                weights_6_load_reg_604 <= weights_6_q0;
                weights_7_load_reg_609 <= weights_7_q0;
                weights_8_load_reg_614 <= weights_8_q0;
                weights_9_load_reg_619 <= weights_9_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_done, grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_done, ap_CS_fsm_state3, icmp_ln9_fu_370_p2, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln9_fu_370_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln9_fu_376_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_68) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_done)
    begin
        if ((grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_done)
    begin
        if ((grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln9_fu_370_p2)
    begin
        if (((icmp_ln9_fu_370_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln9_fu_370_p2)
    begin
        if (((icmp_ln9_fu_370_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    depth2_o77_read_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_depth2_o77_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            depth2_o77_read <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_depth2_o77_read;
        else 
            depth2_o77_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start <= grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_ap_start_reg;
    grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_ap_start_reg;
    icmp_ln9_fu_370_p2 <= "1" when (indvar_flatten_fu_68 = ap_const_lv5_10) else "0";
    point2_o78_din <= grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_point2_o78_din;

    point2_o78_write_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_point2_o78_write, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            point2_o78_write <= grp_PointwiseConv2d_4_4_12_Pipeline_VITIS_LOOP_25_2_fu_344_point2_o78_write;
        else 
            point2_o78_write <= ap_const_logic_0;
        end if; 
    end process;


    weights_0_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_0_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_0_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_address0;
        else 
            weights_0_address0 <= "XX";
        end if; 
    end process;

    weights_0_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_address1;

    weights_0_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_0_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_0_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_ce0;
        else 
            weights_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_0_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_0_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_0_ce1;
        else 
            weights_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_10_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_10_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_10_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_address0;
        else 
            weights_10_address0 <= "XX";
        end if; 
    end process;

    weights_10_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_address1;

    weights_10_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_10_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_10_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_ce0;
        else 
            weights_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_10_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_10_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_10_ce1;
        else 
            weights_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_11_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_11_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_11_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_address0;
        else 
            weights_11_address0 <= "XX";
        end if; 
    end process;

    weights_11_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_address1;

    weights_11_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_11_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_11_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_ce0;
        else 
            weights_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_11_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_11_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_11_ce1;
        else 
            weights_11_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    weights_12_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_address0;
    weights_12_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_address1;
    weights_12_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_ce0;
    weights_12_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_12_ce1;

    weights_1_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_1_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_1_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_address0;
        else 
            weights_1_address0 <= "XX";
        end if; 
    end process;

    weights_1_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_address1;

    weights_1_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_1_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_ce0;
        else 
            weights_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_1_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_1_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_1_ce1;
        else 
            weights_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_2_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_2_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_2_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_address0;
        else 
            weights_2_address0 <= "XX";
        end if; 
    end process;

    weights_2_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_address1;

    weights_2_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_2_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_2_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_ce0;
        else 
            weights_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_2_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_2_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_2_ce1;
        else 
            weights_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_3_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_3_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_3_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_address0;
        else 
            weights_3_address0 <= "XX";
        end if; 
    end process;

    weights_3_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_address1;

    weights_3_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_3_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_3_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_ce0;
        else 
            weights_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_3_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_3_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_3_ce1;
        else 
            weights_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_4_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_4_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_4_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_address0;
        else 
            weights_4_address0 <= "XX";
        end if; 
    end process;

    weights_4_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_address1;

    weights_4_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_4_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_4_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_ce0;
        else 
            weights_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_4_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_4_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_4_ce1;
        else 
            weights_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_5_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_5_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_5_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_address0;
        else 
            weights_5_address0 <= "XX";
        end if; 
    end process;

    weights_5_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_address1;

    weights_5_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_5_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_5_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_ce0;
        else 
            weights_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_5_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_5_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_5_ce1;
        else 
            weights_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_6_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_6_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_6_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_address0;
        else 
            weights_6_address0 <= "XX";
        end if; 
    end process;

    weights_6_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_address1;

    weights_6_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_6_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_6_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_ce0;
        else 
            weights_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_6_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_6_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_6_ce1;
        else 
            weights_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_7_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_7_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_7_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_address0;
        else 
            weights_7_address0 <= "XX";
        end if; 
    end process;

    weights_7_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_address1;

    weights_7_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_7_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_7_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_ce0;
        else 
            weights_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_7_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_7_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_7_ce1;
        else 
            weights_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_8_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_8_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_8_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_address0;
        else 
            weights_8_address0 <= "XX";
        end if; 
    end process;

    weights_8_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_address1;

    weights_8_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_8_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_8_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_ce0;
        else 
            weights_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_8_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_8_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_8_ce1;
        else 
            weights_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    weights_9_address0_assign_proc : process(ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            weights_9_address0 <= ap_const_lv64_0(2 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_9_address0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_address0;
        else 
            weights_9_address0 <= "XX";
        end if; 
    end process;

    weights_9_address1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_address1;

    weights_9_ce0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_ce0, ap_CS_fsm_state4)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            weights_9_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_9_ce0 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_ce0;
        else 
            weights_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    weights_9_ce1_assign_proc : process(grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            weights_9_ce1 <= grp_PointwiseConv2d_4_4_12_Pipeline_ic_fu_288_weights_9_ce1;
        else 
            weights_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
