-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MNIST_Loop_VITIS_LOOP_226_1_proc6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    point3_o_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    point3_o_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    point3_o_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    point3_o_empty_n : IN STD_LOGIC;
    point3_o_read : OUT STD_LOGIC;
    ostrm_TREADY : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (3 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (3 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (1 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (4 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (5 downto 0);
    ostrm_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    ostrm_TVALID : OUT STD_LOGIC;
    ostrm_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    ostrm_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    ostrm_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    ostrm_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ostrm_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    ostrm_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of MNIST_Loop_VITIS_LOOP_226_1_proc6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_ostrm_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln226_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal point3_o_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ostrm_TDATA_blk_n : STD_LOGIC;
    signal p_read_1_reg_178 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read_2_reg_183 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_read_3_reg_188 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_read_4_reg_193 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_read_5_reg_198 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_last_V_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_207 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_74 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_2_fu_154_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ostrm_TVALID_int_regslice : STD_LOGIC;
    signal ostrm_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_ostrm_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_ostrm_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_ostrm_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_ostrm_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_ostrm_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_ostrm_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_ostrm_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_ostrm_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_ostrm_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_ostrm_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_ostrm_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_ostrm_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_ostrm_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_ostrm_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_ostrm_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_ostrm_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_ostrm_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_ostrm_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_ostrm_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_condition_142 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component MNIST_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component MNIST_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component MNIST_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_ostrm_V_data_V_U : component MNIST_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => point3_o_dout,
        vld_in => ostrm_TVALID_int_regslice,
        ack_in => ostrm_TREADY_int_regslice,
        data_out => ostrm_TDATA,
        vld_out => regslice_both_ostrm_V_data_V_U_vld_out,
        ack_out => ostrm_TREADY,
        apdone_blk => regslice_both_ostrm_V_data_V_U_apdone_blk);

    regslice_both_ostrm_V_keep_V_U : component MNIST_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => p_read_5_reg_198,
        vld_in => ostrm_TVALID_int_regslice,
        ack_in => regslice_both_ostrm_V_keep_V_U_ack_in_dummy,
        data_out => ostrm_TKEEP,
        vld_out => regslice_both_ostrm_V_keep_V_U_vld_out,
        ack_out => ostrm_TREADY,
        apdone_blk => regslice_both_ostrm_V_keep_V_U_apdone_blk);

    regslice_both_ostrm_V_strb_V_U : component MNIST_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => p_read_4_reg_193,
        vld_in => ostrm_TVALID_int_regslice,
        ack_in => regslice_both_ostrm_V_strb_V_U_ack_in_dummy,
        data_out => ostrm_TSTRB,
        vld_out => regslice_both_ostrm_V_strb_V_U_vld_out,
        ack_out => ostrm_TREADY,
        apdone_blk => regslice_both_ostrm_V_strb_V_U_apdone_blk);

    regslice_both_ostrm_V_user_V_U : component MNIST_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => p_read_3_reg_188,
        vld_in => ostrm_TVALID_int_regslice,
        ack_in => regslice_both_ostrm_V_user_V_U_ack_in_dummy,
        data_out => ostrm_TUSER,
        vld_out => regslice_both_ostrm_V_user_V_U_vld_out,
        ack_out => ostrm_TREADY,
        apdone_blk => regslice_both_ostrm_V_user_V_U_apdone_blk);

    regslice_both_ostrm_V_last_V_U : component MNIST_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => tmp_last_V_reg_207,
        vld_in => ostrm_TVALID_int_regslice,
        ack_in => regslice_both_ostrm_V_last_V_U_ack_in_dummy,
        data_out => ostrm_TLAST,
        vld_out => regslice_both_ostrm_V_last_V_U_vld_out,
        ack_out => ostrm_TREADY,
        apdone_blk => regslice_both_ostrm_V_last_V_U_apdone_blk);

    regslice_both_ostrm_V_id_V_U : component MNIST_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => p_read_2_reg_183,
        vld_in => ostrm_TVALID_int_regslice,
        ack_in => regslice_both_ostrm_V_id_V_U_ack_in_dummy,
        data_out => ostrm_TID,
        vld_out => regslice_both_ostrm_V_id_V_U_vld_out,
        ack_out => ostrm_TREADY,
        apdone_blk => regslice_both_ostrm_V_id_V_U_apdone_blk);

    regslice_both_ostrm_V_dest_V_U : component MNIST_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => p_read_1_reg_178,
        vld_in => ostrm_TVALID_int_regslice,
        ack_in => regslice_both_ostrm_V_dest_V_U_ack_in_dummy,
        data_out => ostrm_TDEST,
        vld_out => regslice_both_ostrm_V_dest_V_U_vld_out,
        ack_out => ostrm_TREADY,
        apdone_blk => regslice_both_ostrm_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_142)) then
                if ((icmp_ln226_fu_148_p2 = ap_const_lv1_0)) then 
                    i_fu_74 <= i_2_fu_154_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_74 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                p_read_1_reg_178 <= p_read4;
                p_read_2_reg_183 <= p_read3;
                p_read_3_reg_188 <= p_read2;
                p_read_4_reg_193 <= p_read1;
                p_read_5_reg_198 <= p_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln226_fu_148_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_last_V_reg_207 <= tmp_last_V_fu_160_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, point3_o_empty_n, regslice_both_ostrm_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, ostrm_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_ostrm_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ostrm_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_ostrm_V_data_V_U_apdone_blk = ap_const_logic_1) or (point3_o_empty_n = ap_const_logic_0) or (ostrm_TREADY_int_regslice = ap_const_logic_0))) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, point3_o_empty_n, regslice_both_ostrm_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, ostrm_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_ostrm_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ostrm_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_ostrm_V_data_V_U_apdone_blk = ap_const_logic_1) or (point3_o_empty_n = ap_const_logic_0) or (ostrm_TREADY_int_regslice = ap_const_logic_0))) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, point3_o_empty_n, regslice_both_ostrm_V_data_V_U_apdone_blk, ap_loop_exit_ready_pp0_iter1_reg, ap_start_int, ostrm_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (regslice_both_ostrm_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ostrm_TREADY_int_regslice = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_ostrm_V_data_V_U_apdone_blk = ap_const_logic_1) or (point3_o_empty_n = ap_const_logic_0) or (ostrm_TREADY_int_regslice = ap_const_logic_0))) or ((ap_done_reg = ap_const_logic_1) and (ap_start_int = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(point3_o_empty_n, regslice_both_ostrm_V_data_V_U_apdone_blk, ostrm_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_both_ostrm_V_data_V_U_apdone_blk = ap_const_logic_1) or (point3_o_empty_n = ap_const_logic_0) or (ostrm_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(ostrm_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (ostrm_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_condition_142_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_142 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln226_fu_148_p2, ap_start_int)
    begin
        if (((icmp_ln226_fu_148_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_74, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_74;
        end if; 
    end process;

    i_2_fu_154_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_1));
    icmp_ln226_fu_148_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv4_A) else "0";

    ostrm_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, ostrm_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ostrm_TDATA_blk_n <= ostrm_TREADY_int_regslice;
        else 
            ostrm_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ostrm_TVALID <= regslice_both_ostrm_V_data_V_U_vld_out;

    ostrm_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ostrm_TVALID_int_regslice <= ap_const_logic_1;
        else 
            ostrm_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    point3_o_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, point3_o_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            point3_o_blk_n <= point3_o_empty_n;
        else 
            point3_o_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    point3_o_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            point3_o_read <= ap_const_logic_1;
        else 
            point3_o_read <= ap_const_logic_0;
        end if; 
    end process;

    tmp_last_V_fu_160_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv4_9) else "0";
end behav;
