// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MNIST_LoadWeights_Pipeline_VITIS_LOOP_162_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        wstrm_TVALID,
        wstrm_TDATA,
        wstrm_TREADY,
        wstrm_TKEEP,
        wstrm_TSTRB,
        wstrm_TUSER,
        wstrm_TLAST,
        wstrm_TID,
        wstrm_TDEST,
        depth3_0_address0,
        depth3_0_ce0,
        depth3_0_we0,
        depth3_0_d0,
        depth3_1_address0,
        depth3_1_ce0,
        depth3_1_we0,
        depth3_1_d0,
        depth3_2_address0,
        depth3_2_ce0,
        depth3_2_we0,
        depth3_2_d0,
        depth3_3_address0,
        depth3_3_ce0,
        depth3_3_we0,
        depth3_3_d0,
        depth3_4_address0,
        depth3_4_ce0,
        depth3_4_we0,
        depth3_4_d0,
        depth3_5_address0,
        depth3_5_ce0,
        depth3_5_we0,
        depth3_5_d0,
        depth3_6_address0,
        depth3_6_ce0,
        depth3_6_we0,
        depth3_6_d0,
        depth3_7_address0,
        depth3_7_ce0,
        depth3_7_we0,
        depth3_7_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   wstrm_TVALID;
input  [31:0] wstrm_TDATA;
output   wstrm_TREADY;
input  [3:0] wstrm_TKEEP;
input  [3:0] wstrm_TSTRB;
input  [1:0] wstrm_TUSER;
input  [0:0] wstrm_TLAST;
input  [4:0] wstrm_TID;
input  [5:0] wstrm_TDEST;
output  [4:0] depth3_0_address0;
output   depth3_0_ce0;
output   depth3_0_we0;
output  [31:0] depth3_0_d0;
output  [4:0] depth3_1_address0;
output   depth3_1_ce0;
output   depth3_1_we0;
output  [31:0] depth3_1_d0;
output  [4:0] depth3_2_address0;
output   depth3_2_ce0;
output   depth3_2_we0;
output  [31:0] depth3_2_d0;
output  [4:0] depth3_3_address0;
output   depth3_3_ce0;
output   depth3_3_we0;
output  [31:0] depth3_3_d0;
output  [4:0] depth3_4_address0;
output   depth3_4_ce0;
output   depth3_4_we0;
output  [31:0] depth3_4_d0;
output  [4:0] depth3_5_address0;
output   depth3_5_ce0;
output   depth3_5_we0;
output  [31:0] depth3_5_d0;
output  [4:0] depth3_6_address0;
output   depth3_6_ce0;
output   depth3_6_we0;
output  [31:0] depth3_6_d0;
output  [4:0] depth3_7_address0;
output   depth3_7_ce0;
output   depth3_7_we0;
output  [31:0] depth3_7_d0;

reg ap_idle;
reg wstrm_TREADY;
reg depth3_0_ce0;
reg depth3_0_we0;
reg depth3_1_ce0;
reg depth3_1_we0;
reg depth3_2_ce0;
reg depth3_2_we0;
reg depth3_3_ce0;
reg depth3_3_we0;
reg depth3_4_ce0;
reg depth3_4_we0;
reg depth3_5_ce0;
reg depth3_5_we0;
reg depth3_6_ce0;
reg depth3_6_we0;
reg depth3_7_ce0;
reg depth3_7_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln162_fu_220_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    wstrm_TDATA_blk_n;
wire   [63:0] zext_ln166_fu_258_p1;
reg   [7:0] i_fu_86;
wire   [7:0] add_ln162_fu_226_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_4;
wire   [2:0] trunc_ln166_fu_270_p1;
wire   [31:0] bitcast_ln166_fu_236_p1;
wire   [4:0] lshr_ln_fu_248_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_219;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

MNIST_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if ((icmp_ln162_fu_220_p2 == 1'd0)) begin
            i_fu_86 <= add_ln162_fu_226_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_86 <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_4 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_86;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        depth3_0_ce0 = 1'b1;
    end else begin
        depth3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln166_fu_270_p1 == 3'd0))) begin
        depth3_0_we0 = 1'b1;
    end else begin
        depth3_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        depth3_1_ce0 = 1'b1;
    end else begin
        depth3_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln166_fu_270_p1 == 3'd1))) begin
        depth3_1_we0 = 1'b1;
    end else begin
        depth3_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        depth3_2_ce0 = 1'b1;
    end else begin
        depth3_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln166_fu_270_p1 == 3'd2))) begin
        depth3_2_we0 = 1'b1;
    end else begin
        depth3_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        depth3_3_ce0 = 1'b1;
    end else begin
        depth3_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln166_fu_270_p1 == 3'd3))) begin
        depth3_3_we0 = 1'b1;
    end else begin
        depth3_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        depth3_4_ce0 = 1'b1;
    end else begin
        depth3_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln166_fu_270_p1 == 3'd4))) begin
        depth3_4_we0 = 1'b1;
    end else begin
        depth3_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        depth3_5_ce0 = 1'b1;
    end else begin
        depth3_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln166_fu_270_p1 == 3'd5))) begin
        depth3_5_we0 = 1'b1;
    end else begin
        depth3_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        depth3_6_ce0 = 1'b1;
    end else begin
        depth3_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln166_fu_270_p1 == 3'd6))) begin
        depth3_6_we0 = 1'b1;
    end else begin
        depth3_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1))) begin
        depth3_7_ce0 = 1'b1;
    end else begin
        depth3_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln166_fu_270_p1 == 3'd7))) begin
        depth3_7_we0 = 1'b1;
    end else begin
        depth3_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_220_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        wstrm_TDATA_blk_n = wstrm_TVALID;
    end else begin
        wstrm_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (icmp_ln162_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        wstrm_TREADY = 1'b1;
    end else begin
        wstrm_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln162_fu_226_p2 = (ap_sig_allocacmp_i_4 + 8'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0)));
end

always @ (*) begin
    ap_condition_219 = (~((ap_start_int == 1'b0) | ((icmp_ln162_fu_220_p2 == 1'd0) & (wstrm_TVALID == 1'b0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln166_fu_236_p1 = wstrm_TDATA;

assign depth3_0_address0 = zext_ln166_fu_258_p1;

assign depth3_0_d0 = bitcast_ln166_fu_236_p1;

assign depth3_1_address0 = zext_ln166_fu_258_p1;

assign depth3_1_d0 = bitcast_ln166_fu_236_p1;

assign depth3_2_address0 = zext_ln166_fu_258_p1;

assign depth3_2_d0 = bitcast_ln166_fu_236_p1;

assign depth3_3_address0 = zext_ln166_fu_258_p1;

assign depth3_3_d0 = bitcast_ln166_fu_236_p1;

assign depth3_4_address0 = zext_ln166_fu_258_p1;

assign depth3_4_d0 = bitcast_ln166_fu_236_p1;

assign depth3_5_address0 = zext_ln166_fu_258_p1;

assign depth3_5_d0 = bitcast_ln166_fu_236_p1;

assign depth3_6_address0 = zext_ln166_fu_258_p1;

assign depth3_6_d0 = bitcast_ln166_fu_236_p1;

assign depth3_7_address0 = zext_ln166_fu_258_p1;

assign depth3_7_d0 = bitcast_ln166_fu_236_p1;

assign icmp_ln162_fu_220_p2 = ((ap_sig_allocacmp_i_4 == 8'd192) ? 1'b1 : 1'b0);

assign lshr_ln_fu_248_p4 = {{ap_sig_allocacmp_i_4[7:3]}};

assign trunc_ln166_fu_270_p1 = ap_sig_allocacmp_i_4[2:0];

assign zext_ln166_fu_258_p1 = lshr_ln_fu_248_p4;

endmodule //MNIST_LoadWeights_Pipeline_VITIS_LOOP_162_5
