// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module MNIST_PointwiseConv2d_1_12_10_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        depth3_o79_dout,
        depth3_o79_num_data_valid,
        depth3_o79_fifo_cap,
        depth3_o79_empty_n,
        depth3_o79_read,
        weights_0_address0,
        weights_0_ce0,
        weights_0_q0,
        weights_0_address1,
        weights_0_ce1,
        weights_0_q1,
        weights_1_address0,
        weights_1_ce0,
        weights_1_q0,
        weights_1_address1,
        weights_1_ce1,
        weights_1_q1,
        weights_2_address0,
        weights_2_ce0,
        weights_2_q0,
        weights_2_address1,
        weights_2_ce1,
        weights_2_q1,
        weights_3_address0,
        weights_3_ce0,
        weights_3_q0,
        weights_3_address1,
        weights_3_ce1,
        weights_3_q1,
        weights_4_address0,
        weights_4_ce0,
        weights_4_q0,
        weights_4_address1,
        weights_4_ce1,
        weights_4_q1,
        weights_5_address0,
        weights_5_ce0,
        weights_5_q0,
        weights_5_address1,
        weights_5_ce1,
        weights_5_q1,
        weights_6_address0,
        weights_6_ce0,
        weights_6_q0,
        weights_6_address1,
        weights_6_ce1,
        weights_6_q1,
        weights_7_address0,
        weights_7_ce0,
        weights_7_q0,
        weights_7_address1,
        weights_7_ce1,
        weights_7_q1,
        weights_8_address0,
        weights_8_ce0,
        weights_8_q0,
        weights_8_address1,
        weights_8_ce1,
        weights_8_q1,
        weights_9_address0,
        weights_9_ce0,
        weights_9_q0,
        weights_9_address1,
        weights_9_ce1,
        weights_9_q1,
        weights_10_address0,
        weights_10_ce0,
        weights_10_q0,
        weights_10_address1,
        weights_10_ce1,
        weights_10_q1,
        point3_o80_din,
        point3_o80_num_data_valid,
        point3_o80_fifo_cap,
        point3_o80_full_n,
        point3_o80_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] depth3_o79_dout;
input  [1:0] depth3_o79_num_data_valid;
input  [1:0] depth3_o79_fifo_cap;
input   depth3_o79_empty_n;
output   depth3_o79_read;
output  [3:0] weights_0_address0;
output   weights_0_ce0;
input  [31:0] weights_0_q0;
output  [3:0] weights_0_address1;
output   weights_0_ce1;
input  [31:0] weights_0_q1;
output  [3:0] weights_1_address0;
output   weights_1_ce0;
input  [31:0] weights_1_q0;
output  [3:0] weights_1_address1;
output   weights_1_ce1;
input  [31:0] weights_1_q1;
output  [3:0] weights_2_address0;
output   weights_2_ce0;
input  [31:0] weights_2_q0;
output  [3:0] weights_2_address1;
output   weights_2_ce1;
input  [31:0] weights_2_q1;
output  [3:0] weights_3_address0;
output   weights_3_ce0;
input  [31:0] weights_3_q0;
output  [3:0] weights_3_address1;
output   weights_3_ce1;
input  [31:0] weights_3_q1;
output  [3:0] weights_4_address0;
output   weights_4_ce0;
input  [31:0] weights_4_q0;
output  [3:0] weights_4_address1;
output   weights_4_ce1;
input  [31:0] weights_4_q1;
output  [3:0] weights_5_address0;
output   weights_5_ce0;
input  [31:0] weights_5_q0;
output  [3:0] weights_5_address1;
output   weights_5_ce1;
input  [31:0] weights_5_q1;
output  [3:0] weights_6_address0;
output   weights_6_ce0;
input  [31:0] weights_6_q0;
output  [3:0] weights_6_address1;
output   weights_6_ce1;
input  [31:0] weights_6_q1;
output  [3:0] weights_7_address0;
output   weights_7_ce0;
input  [31:0] weights_7_q0;
output  [3:0] weights_7_address1;
output   weights_7_ce1;
input  [31:0] weights_7_q1;
output  [3:0] weights_8_address0;
output   weights_8_ce0;
input  [31:0] weights_8_q0;
output  [3:0] weights_8_address1;
output   weights_8_ce1;
input  [31:0] weights_8_q1;
output  [3:0] weights_9_address0;
output   weights_9_ce0;
input  [31:0] weights_9_q0;
output  [3:0] weights_9_address1;
output   weights_9_ce1;
input  [31:0] weights_9_q1;
output  [3:0] weights_10_address0;
output   weights_10_ce0;
input  [31:0] weights_10_q0;
output  [3:0] weights_10_address1;
output   weights_10_ce1;
input  [31:0] weights_10_q1;
output  [31:0] point3_o80_din;
input  [1:0] point3_o80_num_data_valid;
input  [1:0] point3_o80_fifo_cap;
input   point3_o80_full_n;
output   point3_o80_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg depth3_o79_read;
reg point3_o80_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_done;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_idle;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_ready;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_depth3_o79_read;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_ce1;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_address0;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_ce0;
wire   [3:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_address1;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_ce1;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_916_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_916_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_815_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_815_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_714_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_714_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_613_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_613_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_512_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_512_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_411_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_411_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_310_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_310_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_29_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_29_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_18_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_18_out_ap_vld;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add277_out;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add277_out_ap_vld;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_done;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_idle;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_ready;
wire   [31:0] grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_point3_o80_din;
wire    grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_point3_o80_write;
reg    grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start_reg;
reg    ap_block_state1_ignore_call13;
wire    ap_CS_fsm_state2;
reg    grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start_reg = 1'b0;
#0 grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start_reg = 1'b0;
end

MNIST_PointwiseConv2d_1_12_10_Pipeline_ic grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start),
    .ap_done(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_done),
    .ap_idle(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_idle),
    .ap_ready(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_ready),
    .depth3_o79_dout(depth3_o79_dout),
    .depth3_o79_num_data_valid(2'd0),
    .depth3_o79_fifo_cap(2'd0),
    .depth3_o79_empty_n(depth3_o79_empty_n),
    .depth3_o79_read(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_depth3_o79_read),
    .weights_0_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_address0),
    .weights_0_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_ce0),
    .weights_0_q0(weights_0_q0),
    .weights_0_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_address1),
    .weights_0_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_ce1),
    .weights_0_q1(weights_0_q1),
    .weights_1_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_address0),
    .weights_1_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_ce0),
    .weights_1_q0(weights_1_q0),
    .weights_1_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_address1),
    .weights_1_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_ce1),
    .weights_1_q1(weights_1_q1),
    .weights_2_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_address0),
    .weights_2_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_ce0),
    .weights_2_q0(weights_2_q0),
    .weights_2_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_address1),
    .weights_2_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_ce1),
    .weights_2_q1(weights_2_q1),
    .weights_3_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_address0),
    .weights_3_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_ce0),
    .weights_3_q0(weights_3_q0),
    .weights_3_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_address1),
    .weights_3_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_ce1),
    .weights_3_q1(weights_3_q1),
    .weights_4_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_address0),
    .weights_4_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_ce0),
    .weights_4_q0(weights_4_q0),
    .weights_4_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_address1),
    .weights_4_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_ce1),
    .weights_4_q1(weights_4_q1),
    .weights_5_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_address0),
    .weights_5_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_ce0),
    .weights_5_q0(weights_5_q0),
    .weights_5_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_address1),
    .weights_5_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_ce1),
    .weights_5_q1(weights_5_q1),
    .weights_6_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_address0),
    .weights_6_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_ce0),
    .weights_6_q0(weights_6_q0),
    .weights_6_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_address1),
    .weights_6_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_ce1),
    .weights_6_q1(weights_6_q1),
    .weights_7_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_address0),
    .weights_7_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_ce0),
    .weights_7_q0(weights_7_q0),
    .weights_7_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_address1),
    .weights_7_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_ce1),
    .weights_7_q1(weights_7_q1),
    .weights_8_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_address0),
    .weights_8_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_ce0),
    .weights_8_q0(weights_8_q0),
    .weights_8_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_address1),
    .weights_8_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_ce1),
    .weights_8_q1(weights_8_q1),
    .weights_9_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_address0),
    .weights_9_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_ce0),
    .weights_9_q0(weights_9_q0),
    .weights_9_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_address1),
    .weights_9_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_ce1),
    .weights_9_q1(weights_9_q1),
    .weights_10_address0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_address0),
    .weights_10_ce0(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_ce0),
    .weights_10_q0(weights_10_q0),
    .weights_10_address1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_address1),
    .weights_10_ce1(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_ce1),
    .weights_10_q1(weights_10_q1),
    .add27_916_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_916_out),
    .add27_916_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_916_out_ap_vld),
    .add27_815_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_815_out),
    .add27_815_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_815_out_ap_vld),
    .add27_714_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_714_out),
    .add27_714_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_714_out_ap_vld),
    .add27_613_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_613_out),
    .add27_613_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_613_out_ap_vld),
    .add27_512_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_512_out),
    .add27_512_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_512_out_ap_vld),
    .add27_411_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_411_out),
    .add27_411_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_411_out_ap_vld),
    .add27_310_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_310_out),
    .add27_310_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_310_out_ap_vld),
    .add27_29_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_29_out),
    .add27_29_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_29_out_ap_vld),
    .add27_18_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_18_out),
    .add27_18_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_18_out_ap_vld),
    .add277_out(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add277_out),
    .add277_out_ap_vld(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add277_out_ap_vld)
);

MNIST_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2 grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start),
    .ap_done(grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_done),
    .ap_idle(grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_idle),
    .ap_ready(grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_ready),
    .point3_o80_din(grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_point3_o80_din),
    .point3_o80_num_data_valid(2'd0),
    .point3_o80_fifo_cap(2'd0),
    .point3_o80_full_n(point3_o80_full_n),
    .point3_o80_write(grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_point3_o80_write),
    .add277_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add277_out),
    .add27_18_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_18_out),
    .add27_29_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_29_out),
    .add27_310_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_310_out),
    .add27_411_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_411_out),
    .add27_512_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_512_out),
    .add27_613_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_613_out),
    .add27_714_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_714_out),
    .add27_815_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_815_out),
    .add27_916_reload(grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_add27_916_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_ready == 1'b1)) begin
            grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_ready == 1'b1)) begin
            grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        depth3_o79_read = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_depth3_o79_read;
    end else begin
        depth3_o79_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        point3_o80_write = grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_point3_o80_write;
    end else begin
        point3_o80_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call13 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start = grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_ap_start_reg;

assign grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_ap_start_reg;

assign point3_o80_din = grp_PointwiseConv2d_1_12_10_Pipeline_VITIS_LOOP_25_2_fu_122_point3_o80_din;

assign weights_0_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_address0;

assign weights_0_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_address1;

assign weights_0_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_ce0;

assign weights_0_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_0_ce1;

assign weights_10_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_address0;

assign weights_10_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_address1;

assign weights_10_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_ce0;

assign weights_10_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_10_ce1;

assign weights_1_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_address0;

assign weights_1_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_address1;

assign weights_1_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_ce0;

assign weights_1_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_1_ce1;

assign weights_2_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_address0;

assign weights_2_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_address1;

assign weights_2_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_ce0;

assign weights_2_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_2_ce1;

assign weights_3_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_address0;

assign weights_3_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_address1;

assign weights_3_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_ce0;

assign weights_3_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_3_ce1;

assign weights_4_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_address0;

assign weights_4_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_address1;

assign weights_4_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_ce0;

assign weights_4_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_4_ce1;

assign weights_5_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_address0;

assign weights_5_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_address1;

assign weights_5_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_ce0;

assign weights_5_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_5_ce1;

assign weights_6_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_address0;

assign weights_6_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_address1;

assign weights_6_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_ce0;

assign weights_6_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_6_ce1;

assign weights_7_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_address0;

assign weights_7_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_address1;

assign weights_7_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_ce0;

assign weights_7_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_7_ce1;

assign weights_8_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_address0;

assign weights_8_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_address1;

assign weights_8_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_ce0;

assign weights_8_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_8_ce1;

assign weights_9_address0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_address0;

assign weights_9_address1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_address1;

assign weights_9_ce0 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_ce0;

assign weights_9_ce1 = grp_PointwiseConv2d_1_12_10_Pipeline_ic_fu_84_weights_9_ce1;

endmodule //MNIST_PointwiseConv2d_1_12_10_s
